(function(root){'use strict';
const PREFIX='PRINT3D_ATTACHMENTS_V1\n',MAX_FILE=25*1024*1024,MAX_COUNT=8;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='lcrdmksxkgwqkmhfwjan.supabase.co'&&u.pathname.startsWith('/storage/v1/object/public/uploads/')?u.href:null}catch(e){return null}}
function encode(text,files){return files.length?PREFIX+JSON.stringify({text,files:files.map(({url,name,size,type})=>({url,name,size,type}))}):text||null}
function decode(body){if(typeof body!=='string'||!body.startsWith(PREFIX))return {text:body||'',files:[]};try{const data=JSON.parse(body.slice(PREFIX.length));if(typeof data.text!=='string'||!Array.isArray(data.files)||data.files.length>MAX_COUNT)throw Error();const files=data.files.map(f=>{const url=safeURL(f.url);if(!url||typeof f.name!=='string'||!Number.isFinite(f.size)||f.size<0||f.size>MAX_FILE)throw Error();return {...f,url}});return {text:data.text,files}}catch(e){return {text:body,files:[]}}}
const size=n=>n<1024?`${n} Б`:n<1024*1024?`${(n/1024).toFixed(1)} КБ`:`${(n/1024/1024).toFixed(1)} МБ`;
const isPhoto=f=>['image/jpeg','image/png','image/webp','image/gif','image/avif'].includes(f.type);
function attachments(body){return decode(body).files.map(f=>`<a class="chat-file" href="${escape(f.url)}" target="_blank" rel="noopener noreferrer" download="${escape(f.name)}">${isPhoto(f)?`<img src="${escape(f.url)}" loading="lazy" alt="${escape(f.name)}">`:''}<span>↗ ${escape(f.name)}</span><small>${size(f.size)}</small></a>`).join('')}
const api={encode,decode,attachments,size,safeURL};if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof document==='undefined')return;
const drafts=new Map();let current=null;const draft=uid=>{if(!drafts.has(uid))drafts.set(uid,{text:'',files:[],busy:false});return drafts.get(uid)};
const replies=['Вітаю! Замовлення отримав, зараз перевірю модель і напишу деталі.','Уточни, будь ласка, колір, матеріал і кількість деталей.','Модель потребує невеликої правки перед друком. Зараз поясню, що саме.','Розрахунок готовий. Вартість: ___ грн. Орієнтовний час друку: ___.','Друк розпочався! Процес можна подивитися у своєму замовленні.','Замовлення готове! Узгодимо отримання або відправлення.','Замовлення відправлено. Номер накладної: ___.'];
function paint(){const box=document.getElementById('chat-attachments');if(!box||!current)return;const d=draft(current);box.innerHTML=d.files.map((f,i)=>`<div class="chat-selected">${f.preview?`<img src="${f.preview}" alt="">`:''}<span>${escape(f.name)}<small>${size(f.size)}</small></span><button type="button" data-chat="remove" data-index="${i}" aria-label="Прибрати ${escape(f.name)}" ${d.busy?'disabled':''}>×</button></div>`).join('');document.querySelectorAll('.cin input,.cin button,.chat-quick button').forEach(el=>el.disabled=d.busy);document.querySelector('[data-a="msg"]')?.setAttribute('aria-busy',String(d.busy))}
function clear(uid){const d=draft(uid);d.files.forEach(f=>{if(f.preview)URL.revokeObjectURL(f.preview)});d.files=[];d.text='';if(current===uid){const input=document.getElementById('cin');if(input)input.value='';paint()}}
function mount(uid,admin){current=uid;if(!uid)return;const d=draft(uid),input=document.getElementById('cin');if(!input)return;input.value=d.text;input.oninput=()=>d.text=input.value;const quick=document.getElementById('chat-quick');if(quick){quick.hidden=!admin;quick.innerHTML=admin?`<button class="chip" type="button" data-chat="quick-toggle" aria-expanded="false">Готові відповіді ▾</button><div id="chat-replies" hidden>${replies.map((text,i)=>`<button type="button" data-chat="reply" data-index="${i}">${escape(text)}</button>`).join('')}</div>`:''}paint()}
document.addEventListener('change',e=>{const input=e.target;if(!input.matches('#cimg,#cphoto')||!current)return;const d=draft(current),error=document.getElementById('chat-file-error');if(d.busy){input.value='';return}let message='';for(const f of input.files){if(d.files.length>=MAX_COUNT){message='До 8 вкладень в одному повідомленні.';break}if(f.size>MAX_FILE){message=`${f.name}: максимальний розмір — 25 МБ.`;continue}d.files.push({file:f,name:f.name,size:f.size,type:f.type,preview:isPhoto(f)?URL.createObjectURL(f):null})}input.value='';if(error)error.textContent=message;paint()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-chat]');if(!b||!current)return;const d=draft(current);if(d.busy)return;const action=b.dataset.chat;if(action==='remove'){const [f]=d.files.splice(+b.dataset.index,1);if(f?.preview)URL.revokeObjectURL(f.preview);paint()}if(action==='quick-toggle'){const panel=document.getElementById('chat-replies');panel.hidden=!panel.hidden;b.setAttribute('aria-expanded',String(!panel.hidden))}if(action==='reply'){const input=document.getElementById('cin');input.value+=(input.value?'\n':'')+replies[+b.dataset.index];d.text=input.value;input.focus();document.getElementById('chat-replies').hidden=true;document.querySelector('[data-chat="quick-toggle"]').setAttribute('aria-expanded','false')}});
const style=document.createElement('style');style.textContent='.chat-file{display:block;color:inherit;text-decoration:none;border:1px solid #ffffff25;border-radius:12px;padding:8px;margin:4px 0;background:#0002}.chat-file span{display:block}.chat-file img{max-height:260px;object-fit:contain}.chat-attachments{display:flex;gap:8px;overflow-x:auto;flex-shrink:0}.chat-selected{display:flex;align-items:center;gap:6px;max-width:240px;padding:6px;border:1px solid var(--line);border-radius:12px;margin-top:8px;font-size:12px}.chat-selected img{height:44px;width:44px;object-fit:cover;border-radius:8px}.chat-selected span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chat-selected small{display:block;color:var(--muted)}.chat-selected button{flex:none;background:none;border:0;color:var(--text);font-size:24px;cursor:pointer}.chat-quick{margin-top:8px;position:relative;flex-shrink:0}.chat-quick [hidden]{display:none!important}#chat-replies{position:absolute;bottom:44px;left:0;right:0;z-index:5;max-height:300px;overflow:auto;border:1px solid var(--line);border-radius:16px;background:#1c130f;padding:6px;box-shadow:0 10px 40px #0009}#chat-replies button{display:block;width:100%;text-align:left;padding:12px;border:0;border-radius:10px;background:none;color:var(--text);cursor:pointer;font:14px var(--f)}#chat-replies button:hover{background:#ffffff10}#chat-file-error:empty{display:none}#chat-file-error{font-size:12px;margin:6px 0}.cin{flex-wrap:wrap}.cin #cin{flex:1;min-width:90px}.cin .btn{padding:12px 10px}.cart-undo{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);z-index:1100;max-width:calc(100vw - 24px);width:400px;display:flex;gap:12px;align-items:center;padding:14px 18px;background:#20150ff5;border:1px solid #ff8a1f66;border-radius:18px;box-shadow:0 10px 40px #0009}.cart-undo span{flex:1;font-size:14px}.cart-undo button{background:none;border:0;color:#ffab5c;cursor:pointer;padding:8px;font:600 14px var(--f)}';document.head.appendChild(style);
root.Print3DChat={...api,mount,files:uid=>draft(uid).files.map(f=>f.file),busy(uid,value){draft(uid).busy=value;if(uid===current)paint()},clear};
})(typeof window!=='undefined'?window:globalThis);
