(function(root){'use strict';
const icons={move:'<path d="M12 3v18M3 12h18M9 6l3-3 3 3M9 18l3 3 3-3M6 9l-3 3 3 3M18 9l3 3-3 3"/>',rotate:'<path d="M20 7v5h-5M20 12a8 8 0 1 0-2 6"/>',scale:'<path d="M14 3h7v7M21 3l-8 8M10 21H3v-7M3 21l8-8"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',reset:'<path d="M3 10V4h6M3 4l6 6M4 15a8 8 0 1 0 5-11"/>'};
const icon=key=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[key]}</svg>`;
function mount({T,TransformControls,host,scene,camera,controls,mesh,getItems,onTransform,fit,enabled=()=>true}){
 const canvas=host.querySelector('canvas'),proxy=new T.Object3D();scene.add(proxy);
 const gizmo=new TransformControls(camera,canvas);scene.add(gizmo);gizmo.setSize(.85);gizmo.setTranslationSnap(.1);gizmo.setRotationSnap(Math.PI/36);gizmo.setScaleSnap(.01);
 const outline=new T.LineSegments(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xffad50,depthTest:false,transparent:true,opacity:.9}));outline.renderOrder=100;scene.add(outline);outline.visible=false;
 const panel=document.createElement('div');panel.className='edit-tools';panel.innerHTML=`<select aria-label="Вибрати перегородку або комірку"><option value="">Вибери елемент у 3D</option></select><div class="edit-modes">${[['translate','move','Перемістити'],['rotate','rotate','Обертати'],['scale','scale','Масштаб']].map(([mode,svg,label])=>`<button type="button" data-mode="${mode}" title="${label}" aria-label="${label}">${icon(svg)}</button>`).join('')}<span></span><button type="button" data-view="rotate" title="Повернути огляд" aria-label="Повернути огляд">${icon('rotate')}</button><button type="button" data-view="in" title="Наблизити" aria-label="Наблизити">${icon('plus')}</button><button type="button" data-view="out" title="Віддалити" aria-label="Віддалити">${icon('minus')}</button><button type="button" data-view="fit" title="Повернути камеру" aria-label="Повернути камеру">${icon('reset')}</button></div><small role="status">Натисни на внутрішню стінку або комірку.</small>`;host.appendChild(panel);
 const select=panel.querySelector('select'),status=panel.querySelector('small'),modeButtons=[...panel.querySelectorAll('[data-mode]')];let selected=null,mode='translate',down=null,lastOutline='',lastOptions='',changing=false,disposed=false;
 const find=()=>getItems().find(item=>item.id===selected);
 function configure(item){if(!item)return;if(mode==='rotate'&&!item.rotate||mode==='scale'&&!item.scale)mode='translate';gizmo.setMode(mode);gizmo.setSpace(mode==='translate'?'world':'local');gizmo.showX=mode==='rotate'?false:mode==='scale'?true:item.axes.includes('x');gizmo.showY=mode==='rotate';gizmo.showZ=mode==='rotate'?false:mode==='scale'?!item.round:item.axes.includes('z');modeButtons.forEach(b=>{b.disabled=!item||(b.dataset.mode==='rotate'&&!item.rotate)||(b.dataset.mode==='scale'&&!item.scale);b.classList.toggle('on',b.dataset.mode===mode)})}
 function sync(item){proxy.position.set(...item.position);proxy.rotation.set(0,item.rotation||0,0);proxy.scale.set(item.scaleX||1,1,item.scaleZ||1);proxy.updateMatrixWorld();configure(item);const key=JSON.stringify([item.size,item.round]);if(key!==lastOutline){lastOutline=key;const geometry=item.round?new T.CylinderGeometry(item.size[0]/2,item.size[0]/2,item.size[1],48):new T.BoxGeometry(...item.size);outline.geometry.dispose();outline.geometry=new T.EdgesGeometry(geometry);geometry.dispose()}outline.position.set(...item.position);outline.rotation.set(0,item.rotation||0,0);outline.visible=true}
 function choose(id){selected=id||null;select.value=id||'';lastOutline='';const item=find();if(!item){gizmo.detach();outline.visible=false;modeButtons.forEach(b=>b.disabled=true);status.textContent='Натисни на внутрішню стінку або комірку.';return}sync(item);gizmo.attach(proxy);status.textContent=item.label+' · тягни 3D-стрілку';}
 select.onchange=()=>choose(select.value);
 panel.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode){mode=b.dataset.mode;configure(find());status.textContent=mode==='scale'?'Масштаб змінює розмір отвору. Перевір посадку предмета.':mode==='rotate'?'Тягни дугу навколо вибраної комірки.':'Тягни 3D-стрілку вздовж потрібної осі.';return}const action=b.dataset.view;if(action==='fit'){fit();return}const offset=camera.position.clone().sub(controls.target);if(action==='rotate')offset.applyAxisAngle(new T.Vector3(0,1,0),Math.PI/8);else offset.multiplyScalar(action==='in'?.8:1.25);const distance=Math.max(controls.minDistance,Math.min(controls.maxDistance,offset.length()));offset.setLength(distance);camera.position.copy(controls.target).add(offset);controls.update()};
 gizmo.addEventListener('dragging-changed',e=>{controls.enabled=!e.value});
 gizmo.addEventListener('objectChange',()=>{if(changing||!selected||!enabled())return;changing=true;try{const result=onTransform(selected,{position:proxy.position.toArray(),rotation:proxy.rotation.y,scaleX:proxy.scale.x,scaleZ:proxy.scale.z},mode);const item=find();if(item)sync(item);if(result?.error)status.textContent=result.error;else if(item)status.textContent=item.label+(mode==='scale'?` · ${(proxy.scale.x*100).toFixed(0)}%`:' · положення збережено')}finally{changing=false}});
 const ray=new T.Raycaster(),pointer=new T.Vector2();
 const pointerDown=e=>{down={id:e.pointerId,x:e.clientX,y:e.clientY,gizmo:!!gizmo.axis||gizmo.dragging};};
 const pointerUp=e=>{if(!down||down.id!==e.pointerId)return;const start=down;down=null;if(start.gizmo||Math.hypot(e.clientX-start.x,e.clientY-start.y)>6||!enabled())return;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);camera.updateMatrixWorld();mesh.updateMatrixWorld();ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(mesh,false)[0];if(!hit){choose(null);return}const items=getItems(),p=hit.point,candidates=items.filter(item=>{const v=p.clone().sub(new T.Vector3(...item.position)).applyAxisAngle(new T.Vector3(0,1,0),-(item.rotation||0));return Math.abs(v.x)<=item.size[0]/2+1.5&&Math.abs(v.y)<=item.size[1]/2+1.5&&Math.abs(v.z)<=item.size[2]/2+1.5});candidates.sort((a,b)=>p.distanceTo(new T.Vector3(...a.position))-p.distanceTo(new T.Vector3(...b.position)));choose(candidates[0]?.id||null)};
 const cancel=()=>{down=null;if(gizmo.dragging){gizmo.reset();gizmo.pointerUp({button:0})}controls.enabled=true};
 canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',cancel);
 choose(null);
 return {choose,update(){if(disposed)return;const active=enabled();panel.hidden=!active;if(!active){gizmo.visible=false;outline.visible=false;return}const items=getItems(),options=items.map(x=>x.id+':'+x.label).join('|');if(options!==lastOptions){lastOptions=options;select.replaceChildren(new Option('Вибери елемент у 3D',''),...items.map(x=>new Option(x.label,x.id)));select.value=selected||''}const item=find();if(!item){if(selected)choose(null);return}gizmo.visible=true;if(!gizmo.dragging)sync(item)},dispose(){if(disposed)return;disposed=true;controls.enabled=true;canvas.removeEventListener('pointerdown',pointerDown);canvas.removeEventListener('pointerup',pointerUp);canvas.removeEventListener('pointercancel',cancel);gizmo.detach();gizmo.dispose();scene.remove(gizmo,proxy,outline);outline.geometry.dispose();outline.material.dispose();panel.remove()}};
}
const style=document.createElement('style');style.textContent='.org-preview{position:relative}.edit-tools{position:absolute;left:8px;right:8px;bottom:8px;display:flex;flex-direction:column;gap:5px;padding:8px;border:1px solid #ffffff1a;border-radius:14px;background:#140e09e8;backdrop-filter:blur(8px)}.edit-tools[hidden]{display:none!important}#app .edit-tools select{font-size:13px;padding:7px 30px 7px 10px;border-radius:8px}.edit-modes{display:flex;gap:4px;align-items:center}.edit-modes span{flex:1}.edit-modes button{display:grid;place-items:center;width:34px;height:34px;flex:none;border:1px solid #ffffff25;border-radius:9px;background:#ffffff08;color:#d4c4b7;cursor:pointer}.edit-modes button.on{background:#ff8a1f25;border-color:#ff8a1f;color:#ffab5c}.edit-modes button:disabled{opacity:.3;cursor:default}.edit-modes svg{width:19px;height:19px}.edit-tools small{font:11px sans-serif;color:#c7b5a4;line-height:1.3}.edit-modes button:focus-visible{outline:2px solid #ff8a1f}';document.head.appendChild(style);
root.Print3DWallHandles={mount};
})(window);
