(function(root){'use strict';
let session=null,serial=0;
const svg=(name)=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+({move:'<path d="M12 3v18M3 12h18M9 6l3-3 3 3M9 18l3 3 3-3M6 9l-3 3 3 3M18 9l3 3-3 3"/>',rotate:'<path d="M20 8a8 8 0 1 0 1 6M20 3v5h-5"/>',scale:'<path d="M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5M4 4l6 6M20 20l-6-6"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',fit:'<path d="M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5"/>'}[name]||'')+'</svg>';
function html(){return `<section class="card2 studio flexi-studio" id="flexi-studio"><div><span class="pill">PRINT3D / FLEXI</span><h2>Гнучкі моделі</h2><p class="mut">Завантаж модель, поклади її животом на стіл і розстав негативні різаки. AI генерацію з опису ще не підключено.</p><label class="f"><span>Модель STL · до 15 МБ / 300 000 граней</span><input type="file" accept=".stl" data-flexi-file="model"></label><p class="mut" id="flexi-model-name">Модель ще не завантажена</p><label class="f"><span>Довжина моделі, мм</span><input type="number" min="10" max="400" step="1" value="150" data-flexi-size></label><div class="rw flexi-wrap"><button class="chip" data-flexi="model-x">Повернути модель X · 90°</button><button class="chip" data-flexi="model-z">Повернути модель Z · 90°</button><button class="chip" data-flexi="bed">Поставити на стіл</button></div><label class="rw"><input type="checkbox" data-flexi-floor> Зробити плаский низ: зрізати 0,4 мм</label><hr><h3>Різаки суглобів</h3><p class="mut">Кожен різак — окрема деталь. Вибери його у 3D або в списку; рухай стрілками, обертай кільцями й масштабуй ручками.</p><div class="rw flexi-wrap"><button class="chip" data-flexi="add">+ Суглоб</button><button class="chip" data-flexi="duplicate">Дублювати</button><button class="chip" data-flexi="remove">Видалити вибраний</button></div><div id="flexi-cuts"></div><label class="f"><span>Завантажити інший негативний різак STL</span><input type="file" accept=".stl" data-flexi-file="cutter"></label><p class="mut"><a class="link" href="https://makerworld.com/ru/models/668019-flexi-cutter#profileId-595621" target="_blank" rel="noopener">Flexi Cutter · джерело різака</a></p><p id="flexi-status" class="mut" role="status" aria-live="polite">Завантаж модель, щоб почати.</p><div class="rw flexi-wrap"><button class="btn" data-flexi="apply">Застосувати вирізання</button><button class="chip" data-flexi="edit">Повернутися до редагування</button><button class="btn" data-flexi="download">Завантажити STL</button></div><p class="mut">Масштабування різака змінює також зазори. Перевір суглоб у слайсері та надрукуй тест перед повною моделлю.</p></div><div class="studio-right"><div class="org-preview" id="flexi-preview">Завантаження 3D…</div><div class="rw flexi-wrap"><button class="chip" data-flexi="fit">Вся модель</button><button class="chip" data-flexi="top">Вигляд зверху</button><label class="f"><span>Колір прев’ю</span><input type="color" value="#ff8a1f" data-flexi-color></label></div><p class="mut">STL у міліметрах. Напівпрозорі різаки не входять у завантажений файл.</p></div></section>`}
function dispose(){const s=session;session=null;if(!s)return;s.closed=true;s.worker?.terminate();clearTimeout(s.workerTimeout);s.cutterGeometry?.dispose();s.resize?.disconnect();cancelAnimationFrame(s.frame);s.controls?.dispose();s.gizmo?.dispose();s.renderer?.dispose();s.scene?.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())});s.host.removeEventListener('click',s.click);s.host.removeEventListener('change',s.change)}
async function mount(load3){dispose();const host=document.getElementById('flexi-studio');if(!host)return;const s=session={host,cuts:[],selected:null,mode:'translate',busy:false,closed:false,revision:0,loadSerial:0,result:null,worker:null};const alive=()=>session===s&&!s.closed&&host.isConnected;const status=(text,error=false)=>{if(!alive())return;const el=host.querySelector('#flexi-status');el.textContent=text;el.className=error?'err':'mut'};s.status=status;
 try{
 const {T,OrbitControls,B}=await load3();const [{TransformControls},{STLLoader},{STLExporter}]=await Promise.all([import(B+'examples/jsm/controls/TransformControls.js/+esm'),import(B+'examples/jsm/loaders/STLLoader.js/+esm'),import(B+'examples/jsm/exporters/STLExporter.js/+esm')]);if(!alive())return;
 const area=host.querySelector('#flexi-preview'),scene=s.scene=new T.Scene(),renderer=s.renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));area.innerHTML='';area.appendChild(renderer.domElement);renderer.domElement.style.touchAction='none';const camera=s.camera=new T.PerspectiveCamera(42,1,.1,5000),controls=s.controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=2000;scene.add(new T.HemisphereLight(0xffffff,0x49301e,2));const light=new T.DirectionalLight(0xffffff,3);light.position.set(80,150,60);scene.add(light);
 const grid=new T.GridHelper(400,40,0x6b4529,0x30241c);grid.material.transparent=true;grid.material.opacity=.5;scene.add(grid);
 const gizmo=s.gizmo=new TransformControls(camera,renderer.domElement);gizmo.setSize(.9);gizmo.setTranslationSnap(.1);gizmo.setRotationSnap(Math.PI/36);gizmo.setScaleSnap(.01);scene.add(gizmo);
 const panel=document.createElement('div');panel.className='edit-tools';panel.innerHTML=`<select aria-label="Вибрати модель або різак"></select><div class="edit-modes">${[['translate','move','Перемістити'],['rotate','rotate','Обертати'],['scale','scale','Масштаб']].map(([mode,icon,label])=>`<button type="button" data-flexi-mode="${mode}" aria-label="${label}" title="${label}">${svg(icon)}</button>`).join('')}<span></span>${[['in','plus','Наблизити'],['out','minus','Віддалити'],['fit','fit','Вся модель']].map(([action,icon,label])=>`<button type="button" data-flexi="${action}" aria-label="${label}" title="${label}">${svg(icon)}</button>`).join('')}</div><small>Вибери різак і тягни 3D-стрілку.</small>`;area.appendChild(panel);const selector=panel.querySelector('select');
 const modelMat=new T.MeshStandardMaterial({color:0xff8a1f,roughness:.8,metalness:0}),cutMat=new T.MeshStandardMaterial({color:0x72cbd5,transparent:true,opacity:.4,depthWrite:false,depthTest:false,roughness:.7,side:T.DoubleSide});
 const geometryPositions=(geometry,matrix)=>{const raw=geometry.index?geometry.toNonIndexed():geometry.clone();raw.applyMatrix4(matrix);const positions=new Float32Array(raw.getAttribute('position').array);raw.dispose();return positions};
 const makeGeometry=p=>{const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(p,3));g.computeVertexNormals();g.computeBoundingBox();return g};
 function bounds(object){object.updateMatrixWorld(true);return new T.Box3().setFromObject(object)}
 function resetResult(){if(s.result){scene.remove(s.result);s.result.geometry.dispose();s.result=null}if(s.model)s.model.visible=true;s.cuts.forEach(c=>c.visible=true)}
 function changed(){s.revision++;resetResult();updateButtons()}
 function bed(){if(!s.model)return;const box=bounds(s.model),center=box.getCenter(new T.Vector3());s.model.position.x-=center.x;s.model.position.z-=center.z;s.model.position.y-=box.min.y;s.model.updateMatrixWorld(true)}
 function fit(top=false){const object=s.result||s.model;const box=object?bounds(object):new T.Box3(new T.Vector3(-50,0,-50),new T.Vector3(50,30,50));const center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()),d=Math.max(...size.toArray(),20)*1.9;controls.target.copy(center);camera.position.copy(center).add(top?new T.Vector3(0,d,.001):new T.Vector3(d*.7,d*.7,d));camera.near=.1;camera.far=Math.max(5000,d*10);camera.updateProjectionMatrix();controls.update()}
 function selected(){return s.selected==='model'?s.model:s.cuts.find(c=>c.userData.id===s.selected)}
 function updateButtons(){host.querySelectorAll('[data-flexi]').forEach(b=>{const k=b.dataset.flexi;b.disabled=s.busy||(!s.model&&!['fit','top','in','out'].includes(k))||(k==='add'&&(!s.cutterGeometry||s.cuts.length>=16))||(['duplicate','remove'].includes(k)&&(!selected()||s.selected==='model'))||(k==='apply'&&!s.cuts.length&&!host.querySelector('[data-flexi-floor]').checked)||(k==='edit'&&!s.result)||(k==='duplicate'&&s.cuts.length>=16)});host.querySelectorAll('input').forEach(el=>el.disabled=s.busy);panel.querySelectorAll('[data-flexi-mode]').forEach(b=>{b.disabled=s.busy||!selected();b.classList.toggle('on',b.dataset.flexiMode===s.mode)})}
 function choose(id){s.selected=id;selector.value=id||'';const obj=selected();if(obj&&!s.busy&&!s.result){gizmo.setMode(s.mode);gizmo.setSpace(s.mode==='translate'?'world':'local');gizmo.attach(obj)}else gizmo.detach();host.querySelectorAll('[data-flexi-select]').forEach(b=>b.classList.toggle('on',b.dataset.flexiSelect===id));panel.querySelector('small').textContent=id==='model'?'Основна модель · обери режим керування.':obj?'Різак · переміщення, поворот або масштаб.':'Вибери модель або різак.';updateButtons()}
 function list(){selector.replaceChildren(new Option('Вибери деталь',''),...(s.model?[new Option('Основна модель','model')]:[]),...s.cuts.map((c,i)=>new Option('Суглоб '+(i+1),c.userData.id)));host.querySelector('#flexi-cuts').innerHTML=s.cuts.map((c,i)=>`<button class="chip ${s.selected===c.userData.id?'on':''}" data-flexi-select="${c.userData.id}">Суглоб ${i+1}</button>`).join('');choose(s.selected)}
 function add(duplicate=false){if(!s.model||!s.cutterGeometry||s.cuts.length>=16)return;const obj=new T.Mesh(s.cutterGeometry.clone(),cutMat);obj.userData.id='cut'+(++serial);obj.renderOrder=10;const box=bounds(s.model),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());if(duplicate&&selected()&&s.selected!=='model'){const previous=selected();obj.position.copy(previous.position);obj.position.x+=Math.max(size.x*.08,2);obj.quaternion.copy(previous.quaternion);obj.scale.copy(previous.scale)}else{obj.position.copy(center);const csize=s.cutterGeometry.boundingBox.getSize(new T.Vector3());const scale=Math.max(.1,Math.min(10,size.y/Math.max(csize.y,1)*1.05));obj.scale.setScalar(scale)}scene.add(obj);s.cuts.push(obj);s.selected=obj.userData.id;changed();list();status('Різак додано. Постав його в місце з’єднання й перевір масштаб.');}
 async function loadModel(buffer,name){const geometry=new STLLoader().parse(buffer);if(!geometry.getAttribute('position')||geometry.getAttribute('position').count/3>300000){geometry.dispose();throw Error('Модель завелика: максимум 300 000 граней.')}if(!Array.from(geometry.getAttribute('position').array).every(Number.isFinite)){geometry.dispose();throw Error('Модель містить некоректні координати.')}geometry.rotateX(-Math.PI/2);geometry.computeBoundingBox();const size=geometry.boundingBox.getSize(new T.Vector3());if(Math.max(...size.toArray())<.001){geometry.dispose();throw Error('Модель не має об’єму.')}gizmo.detach();resetResult();if(s.model){scene.remove(s.model);s.model.geometry.dispose()}s.cuts.forEach(c=>{scene.remove(c);c.geometry.dispose()});s.cuts=[];const model=s.model=new T.Mesh(geometry,modelMat);model.userData.id='model';scene.add(model);const length=Math.max(10,Math.min(400,+host.querySelector('[data-flexi-size]').value||150));model.scale.setScalar(length/Math.max(size.x,size.z));bed();s.selected='model';changed();list();fit();host.querySelector('#flexi-model-name').textContent=name;status('Модель завантажена. Поверни її животом до столу й додай різаки.');}
 async function loadCutter(buffer){const geometry=new STLLoader().parse(buffer);const p=geometry.getAttribute('position');if(!p||p.count/3>100000||!Array.from(p.array).every(Number.isFinite)){geometry.dispose();throw Error('Різак має бути коректним STL до 100 000 граней.')}geometry.rotateX(-Math.PI/2);geometry.center();geometry.computeBoundingBox();s.cutterGeometry?.dispose();s.cutterGeometry=geometry;updateButtons()}
 function stopBusy(){s.busy=false;controls.enabled=true;list();updateButtons()}
 function apply(){if(!s.model||s.busy)return;s.busy=true;gizmo.detach();updateButtons();status('Будую суглоби… це може зайняти кілька секунд.');s.model.updateMatrixWorld(true);const base=geometryPositions(s.model.geometry,s.model.matrixWorld),cutter=s.cutterGeometry?geometryPositions(s.cutterGeometry,new T.Matrix4()):new Float32Array(),matrices=s.cuts.map(c=>{c.updateMatrixWorld(true);return c.matrixWorld.toArray()}),revision=s.revision;const worker=s.worker=new Worker('flexi-worker.js?v=20261004-flexi40');const timeout=s.workerTimeout=setTimeout(()=>{worker.terminate();if(!alive()||s.worker!==worker)return;s.worker=null;stopBusy();status('Обчислення тривало понад 90 секунд. Зменш кількість граней або різаків.',true)},90000);const finish=()=>{clearTimeout(timeout);s.workerTimeout=null;worker.terminate();if(s.worker===worker)s.worker=null};worker.onerror=()=>{finish();if(!alive())return;stopBusy();status('Не вдалося завантажити обчислювальний модуль. Перевір інтернет і спробуй ще раз.',true)};worker.onmessage=({data})=>{finish();if(!alive())return;stopBusy();if(!data.ok){status(data.error,true);return}if(revision!==s.revision){status('Модель змінилася. Застосуй вирізання знову.',true);return}resetResult();s.result=new T.Mesh(makeGeometry(data.positions),modelMat);scene.add(s.result);s.model.visible=false;s.cuts.forEach(c=>c.visible=false);gizmo.detach();updateButtons();status(`Вирізання завершено · ${data.parts} окремих частин · ${data.triangles.toLocaleString('uk-UA')} граней. Перевір з’єднання в слайсері.`)};worker.postMessage({base,cutter,matrices,floor:host.querySelector('[data-flexi-floor]').checked?.4:0},[base.buffer,cutter.buffer]);}
 function download(){const object=s.result||s.model;if(!object)return;object.updateMatrixWorld(true);const p=geometryPositions(object.geometry,object.matrixWorld);for(let i=0;i<p.length;i+=3){const y=p[i+1];p[i+1]=-p[i+2];p[i+2]=y}const g=makeGeometry(p),mesh=new T.Mesh(g),data=new STLExporter().parse(mesh,{binary:true}),url=URL.createObjectURL(new Blob([data],{type:'model/stl'})),a=document.createElement('a');a.href=url;a.download=s.result?'print3d-flexi.stl':'print3d-model.stl';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);g.dispose();status(s.result?'STL з вирізаними суглобами завантажено.':'STL основної моделі завантажено. Різаки ще не застосовані.');}
 s.click=e=>{const b=e.target.closest('[data-flexi],[data-flexi-mode],[data-flexi-select]');if(!b||s.busy)return;if(b.dataset.flexiSelect){if(s.result)resetResult();choose(b.dataset.flexiSelect);return}if(b.dataset.flexiMode){s.mode=b.dataset.flexiMode;choose(s.selected);return}const action=b.dataset.flexi;if(action==='add')add();else if(action==='duplicate')add(true);else if(action==='remove'){const obj=selected();if(!obj||s.selected==='model')return;gizmo.detach();s.cuts=s.cuts.filter(c=>c!==obj);scene.remove(obj);obj.geometry.dispose();s.selected=s.cuts.at(-1)?.userData.id||'model';changed();list()}else if(action==='apply')apply();else if(action==='download')download();else if(action==='edit'){resetResult();choose(s.selected);status('Можна змінити положення різаків і застосувати їх знову.')}else if(action==='bed'){changed();bed();choose(s.selected)}else if(action==='model-x'||action==='model-z'){if(!s.model)return;changed();if(action==='model-x')s.model.rotateOnWorldAxis(new T.Vector3(1,0,0),Math.PI/2);else s.model.rotateOnWorldAxis(new T.Vector3(0,0,1),Math.PI/2);bed();choose('model');fit()}else if(action==='fit'||action==='top')fit(action==='top');else if(action==='in'||action==='out'){const delta=camera.position.clone().sub(controls.target).multiplyScalar(action==='in'?.8:1.25);delta.setLength(Math.max(controls.minDistance,Math.min(controls.maxDistance,delta.length())));camera.position.copy(controls.target).add(delta);controls.update()}};
 s.change=async e=>{const el=e.target;if(s.busy)return;try{if(el.dataset.flexiFile){const f=el.files?.[0];if(!f)return;if(f.size>15*1024*1024)throw Error('Файл завеликий: максимум 15 МБ.');const ticket=++s.loadSerial,statusText=el.dataset.flexiFile==='model'?'Читаю модель…':'Читаю різак…';status(statusText);const buffer=await f.arrayBuffer();if(!alive()||ticket!==s.loadSerial)return;if(el.dataset.flexiFile==='model')await loadModel(buffer,f.name);else{await loadCutter(buffer);status('Новий різак завантажено. Він використовується для наступних суглобів.');}el.value=''}else if(el.hasAttribute('data-flexi-size')&&s.model){const length=+el.value;if(!Number.isFinite(length)||length<10||length>400)throw Error('Довжина має бути від 10 до 400 мм.');const size=bounds(s.model).getSize(new T.Vector3());changed();s.model.scale.multiplyScalar(length/Math.max(size.x,size.z));bed();choose('model');fit()}else if(el.hasAttribute('data-flexi-floor')){changed();choose(s.selected)}else if(el.hasAttribute('data-flexi-color'))modelMat.color.set(el.value)}catch(e){status(e.message,true)}};
 selector.onchange=()=>{if(s.busy)return;if(s.result)resetResult();choose(selector.value)};host.addEventListener('click',s.click);host.addEventListener('change',s.change);
 gizmo.addEventListener('dragging-changed',e=>{controls.enabled=!e.value;if(!e.value&&selected()){const obj=selected();obj.scale.set(Math.max(.05,Math.min(30,obj.scale.x)),Math.max(.05,Math.min(30,obj.scale.y)),Math.max(.05,Math.min(30,obj.scale.z)));if(obj===s.model)bed();changed();choose(s.selected)}});gizmo.addEventListener('objectChange',()=>{if(s.busy)return;changed()});
 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down={id:e.pointerId,x:e.clientX,y:e.clientY,gizmo:!!gizmo.axis||gizmo.dragging});renderer.domElement.addEventListener('pointerup',e=>{const start=down;down=null;if(!start||start.id!==e.pointerId||start.gizmo||s.busy||s.result||Math.hypot(e.clientX-start.x,e.clientY-start.y)>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects([...s.cuts,...(s.model?[s.model]:[])],false)[0];choose(hit?.object.userData.id||null)});renderer.domElement.addEventListener('pointercancel',()=>{down=null;if(gizmo.dragging){gizmo.reset();gizmo.pointerUp({button:0})}controls.enabled=true});
 s.resize=new ResizeObserver(()=>{if(!alive())return;const width=area.clientWidth,height=area.clientHeight;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix()});s.resize.observe(area);fit();list();function frame(){if(!alive())return;controls.update();renderer.render(scene,camera);s.frame=requestAnimationFrame(frame)}frame();
 const response=await fetch('assets/flexi-cutter.stl.gz');if(!response.ok)throw Error('Не вдалося завантажити стандартний різак.');if(!alive())return;const compressed=await response.arrayBuffer(),magic=new Uint8Array(compressed,0,Math.min(2,compressed.byteLength));const buffer=magic[0]===31&&magic[1]===139?await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer():compressed;if(!alive())return;if(!s.cutterGeometry)await loadCutter(buffer);
 }catch(e){status(e.message||'3D редактор недоступний.',true)}
}
const style=document.createElement('style');style.textContent='.flexi-wrap{flex-wrap:wrap}.flexi-studio hr{border:0;border-top:1px solid var(--line);margin:22px 0}.flexi-studio input[type=number]{max-width:160px}.flexi-studio input[type=file]{max-width:100%;font-size:14px}.flexi-studio #flexi-cuts{display:flex;flex-wrap:wrap;gap:6px;min-height:42px;margin:12px 0}.flexi-studio #flexi-status{min-height:48px}.flexi-studio #flexi-preview{height:520px}.flexi-studio button:disabled{opacity:.4;cursor:default}@media(max-width:760px){.flexi-studio #flexi-preview{height:350px}.flexi-studio .studio-right{position:relative;top:auto}.flexi-studio .studio-right>.mut{display:block}}';document.head.appendChild(style);
root.Print3DFlexiEditor={html,mount,dispose};
})(window);
