(function(){'use strict';
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const active=new WeakMap(),colors=new WeakMap();
function color(material,value){if(!material?.color)return;const previous=colors.get(material);if(previous)cancelAnimationFrame(previous.frame);const target=material.color.clone().set(value);if(reduced()){material.color.copy(target);colors.delete(material);return}
 const state={from:material.color.clone(),target,start:performance.now(),frame:0};colors.set(material,state);
 const tick=now=>{if(colors.get(material)!==state)return;const t=Math.min(1,(now-state.start)/480),ease=t*t*(3-2*t);material.color.copy(state.from).lerp(target,ease);if(t<1)state.frame=requestAnimationFrame(tick);else colors.delete(material)};state.frame=requestAnimationFrame(tick);
}
function cancelColor(material){const state=colors.get(material);if(state)cancelAnimationFrame(state.frame);colors.delete(material)}
function animate(node,frames,options){if(!node||reduced()||!node.animate)return null;active.get(node)?.cancel();const animation=node.animate(frames,options);active.set(node,animation);animation.finished.catch(()=>{}).finally(()=>{if(active.get(node)===animation&&options.fill!=='forwards')active.delete(node)});return animation}
function bounce(node){return animate(node,[{transform:'scale(1)'},{transform:'scale(.85)',offset:.16},{transform:'scale(1.19)',offset:.48},{transform:'scale(.97)',offset:.78},{transform:'scale(1)'}],{duration:540,easing:'cubic-bezier(.22,.8,.3,1)'})}
function snapshot(button){const media=button.closest('.pcard')?.querySelector('.pimg')||button.closest('.sheet')?.querySelector('.media')||button;return {rect:media.getBoundingClientRect(),src:media.querySelector('img')?.src}}
function fly(from,target,icon){if(!target)return;if(reduced()){return}const to=target.getBoundingClientRect(),header=target.closest('.hdr');let ty=to.top+to.height/2;
 if(header){const transform=getComputedStyle(header).transform;if(transform!=='none')ty-=new DOMMatrixReadOnly(transform).m42;header.classList.remove('scroll-hidden')}
 const tx=to.left+to.width/2,size=Math.min(76,Math.max(36,from.rect.width*.3)),x=from.rect.left+from.rect.width/2-size/2,y=from.rect.top+from.rect.height/2-size/2;
 const flight=document.createElement('div');flight.className='motion-flight';flight.setAttribute('aria-hidden','true');Object.assign(flight.style,{left:x+'px',top:y+'px',width:size+'px',height:size+'px'});
 if(from.src){const img=document.createElement('img');img.src=from.src;flight.appendChild(img)}else flight.innerHTML=icon;
 document.body.appendChild(flight);const dx=tx-x-size/2,dy=ty-y-size/2;
 const animation=flight.animate([{transform:'translate3d(0,0,0) scale(1)',opacity:1},{transform:`translate3d(${dx*.36}px,${Math.min(-60,dy*.4-65)}px,0) scale(.86)`,offset:.42,opacity:1},{transform:`translate3d(${dx}px,${dy}px,0) scale(.2)`,opacity:0}],{duration:760,easing:'cubic-bezier(.4,0,.2,1)'});
 animation.finished.then(()=>bounce(target)).catch(()=>{}).finally(()=>flight.remove());setTimeout(()=>flight.remove(),1000);
}
function favorite(button,on){bounce(button);if(!on||reduced()||!button)return;const rect=button.getBoundingClientRect();for(let i=0;i<7;i++){const dot=document.createElement('span');dot.className='motion-heart';dot.textContent=i%2?'♥':'•';dot.setAttribute('aria-hidden','true');Object.assign(dot.style,{left:(rect.left+rect.width/2)+'px',top:(rect.top+rect.height/2)+'px'});document.body.appendChild(dot);const angle=i/7*Math.PI*2,dist=26+i%3*7;const anim=dot.animate([{transform:'translate(-50%,-50%) scale(.3)',opacity:1},{transform:`translate(calc(-50% + ${Math.cos(angle)*dist}px),calc(-50% + ${Math.sin(angle)*dist-14}px)) scale(1)`,opacity:.8,offset:.62},{transform:`translate(calc(-50% + ${Math.cos(angle)*dist*1.2}px),calc(-50% + ${Math.sin(angle)*dist-30}px)) scale(.4)`,opacity:0}],{duration:620,easing:'ease-out'});anim.finished.catch(()=>{}).finally(()=>dot.remove());setTimeout(()=>dot.remove(),900)}}
const origins=new WeakMap(),viewOrigins=new WeakMap();
function anchor(source){if(!source)return null;if(source.rect)return source;const rect=source.getBoundingClientRect();let selector='';if(source.dataset?.a){selector=`${source.tagName?.toLowerCase()||''}[data-a="${CSS.escape(source.dataset.a)}"]`;for(const key of ['n','id'])if(source.dataset[key]!==undefined)selector+=`[data-${key}="${CSS.escape(source.dataset[key])}"]`;}return {source,selector,rect:{left:rect.left,top:rect.top,width:rect.width,height:rect.height}}}
function originRect(origin){if(!origin)return null;let source=origin.source?.isConnected?origin.source:null;if(!source&&origin.selector)source=document.querySelector(origin.selector);const rect=source?.getBoundingClientRect();const result=rect?.width>0&&rect?.height>0?rect:origin.rect;if(!result)return null;return {left:Math.max(-result.width/2,Math.min(innerWidth-result.width/2,result.left)),top:Math.max(-result.height/2,Math.min(innerHeight-result.height/2,result.top)),width:result.width,height:result.height}}
function stop(node){active.get(node)?.cancel();active.delete(node)}
function morph(box,from){if(!from||!box.width||!box.height)return 'translate3d(0,18px,0) scale(.94)';const dx=from.left+from.width/2-box.left-box.width/2,dy=from.top+from.height/2-box.top-box.height/2,sx=Math.max(.008,Math.min(1,from.width/box.width)),sy=Math.max(.008,Math.min(1,from.height/box.height));return `translate3d(${dx}px,${dy}px,0) scale(${sx},${sy})`}
function open(sheet,source){if(!sheet)return null;const origin=anchor(source);origins.set(sheet,origin);stop(sheet);if(sheet.parentElement?.id==='modal')stop(sheet.parentElement);if(reduced())return null;const box=sheet.getBoundingClientRect(),from=originRect(origin);if(sheet.parentElement?.id==='modal'){const backdrop=sheet.parentElement;stop(backdrop);animate(backdrop,[{opacity:0},{opacity:1}],{duration:480,easing:'cubic-bezier(.22,1,.36,1)'})}
 return animate(sheet,[{transform:morph(box,from),opacity:0,borderRadius:'24px'},{transform:'translate3d(0,-2px,0) scale(1.008)',opacity:1,borderRadius:'24px',offset:.84},{transform:'translate3d(0,0,0) scale(1)',opacity:1,borderRadius:'24px'}],{duration:520,easing:'cubic-bezier(.22,1,.36,1)'});
}
function close(sheet,source){if(!sheet)return null;const current=getComputedStyle(sheet),start={transform:current.transform==='none'?'translate3d(0,0,0) scale(1)':current.transform,opacity:current.opacity};stop(sheet);const box=sheet.getBoundingClientRect(),from=originRect(source?anchor(source):origins.get(sheet));if(sheet.parentElement?.id==='modal'){const backdrop=sheet.parentElement,opacity=getComputedStyle(backdrop).opacity;stop(backdrop);animate(backdrop,[{opacity},{opacity:0}],{duration:360,easing:'cubic-bezier(.4,0,.2,1)',fill:'forwards'})}
 return animate(sheet,[{...start,borderRadius:'24px'},{transform:morph(box,from),opacity:0,borderRadius:'24px'}],{duration:360,easing:'cubic-bezier(.4,0,.2,1)',fill:'forwards'});
}
function leaveView(root){if(!root)return Promise.resolve();const origin=viewOrigins.get(root),animation=close(root,origin);return animation?animation.finished.catch(()=>{}):Promise.resolve()}
let revealObserver=null;
const views=new WeakMap(),numberFrames=new WeakMap();
function reveal(root){revealObserver?.disconnect();if(reduced()||!window.IntersectionObserver)return;
 revealObserver=new IntersectionObserver(entries=>{let delay=0;for(const entry of entries){if(!entry.isIntersecting)continue;const card=entry.target;revealObserver.unobserve(card);card.classList.remove('reveal-pending');animate(card,[{opacity:0,transform:'translateY(20px) scale(.98)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:520,delay:Math.min(delay++,5)*55,fill:'backwards',easing:'cubic-bezier(.22,1,.36,1)'});}},{rootMargin:'0px 0px -24px 0px',threshold:.06});
 root.querySelectorAll('.pcard').forEach(card=>{card.classList.add('reveal-pending');revealObserver.observe(card)});
}
function view(root,key,source){const previous=views.get(root);views.set(root,key);if(previous===undefined&&!source){const page=key.split(':')[0];viewOrigins.set(root,anchor(document.querySelector(page==='order'?'.hdr button[data-a="new"]':`.hdr button[data-a="tab"][data-n="${CSS.escape(page)}"]`)))}if(source){viewOrigins.set(root,anchor(source));open(root,source);return}if(previous===key){stop(root);return}animate(root,[{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:340,easing:'cubic-bezier(.22,1,.36,1)'})}
function captureNumbers(root){const values=new Map();root?.querySelectorAll('[data-number-key]').forEach(node=>{const frame=numberFrames.get(node);if(frame)cancelAnimationFrame(frame);values.set(node.dataset.numberKey,Number(node.dataset.numberShown??node.dataset.numberValue))});return values}
function numbers(root,previous){root.querySelectorAll('[data-number-key]').forEach(node=>{const end=Number(node.dataset.numberValue),start=previous.get(node.dataset.numberKey);if(reduced()||start===undefined||start===end||!Number.isFinite(start)||!Number.isFinite(end))return;const began=performance.now(),money=node.dataset.numberMoney==='true',suffix=node.dataset.numberSuffix||'';node.dataset.numberShown=String(start);node.textContent=(money?new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(start):String(Math.round(start)))+suffix;animate(node,[{opacity:.65,transform:'translateY(5px) scale(.96)'},{opacity:1,transform:'translateY(-1px) scale(1.06)',offset:.65},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:360,easing:'cubic-bezier(.22,1,.36,1)'});
 const tick=now=>{if(!node.isConnected){numberFrames.delete(node);return}const t=Math.min(1,(now-began)/360),ease=1-Math.pow(1-t,3),value=start+(end-start)*ease;node.dataset.numberShown=String(value);node.textContent=(money?new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(value):String(Math.round(value)))+suffix;if(t<1)numberFrames.set(node,requestAnimationFrame(tick));else{node.dataset.numberShown=String(end);node.textContent=(money?new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(end):String(end))+suffix;numberFrames.delete(node)}};numberFrames.set(node,requestAnimationFrame(tick));
 })}
function loading(box,label){box.innerHTML='<div class="model-loading" role="status" aria-live="polite"><span class="model-loader" aria-hidden="true"></span><p class="mut"></p></div>';box.querySelector('p').textContent=label;return box.querySelector('p')}
function model(canvas){animate(canvas,[{opacity:0,transform:'scale(.94)'},{opacity:1,transform:'scale(1)'}],{duration:550,easing:'cubic-bezier(.22,1,.36,1)'})}
document.addEventListener('click',e=>{const button=e.target.closest('button');if(button&&!button.disabled)bounce(button)},true);
const style=document.createElement('style');style.textContent=`
.reveal-pending{opacity:0;transform:translateY(20px)}[data-number-key]{display:inline-block;font-variant-numeric:tabular-nums}.model-loading{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;width:100%;height:100%;min-height:180px;text-align:center}.model-loader{width:46px;height:46px;border:2px solid rgba(255,138,31,.15);border-top-color:#ff8a1f;border-right-color:#ff8a1f;border-radius:50%;animation:model-spin 1.15s linear infinite}.model-loading p{margin:0}@keyframes model-spin{to{transform:rotate(360deg)}}
.motion-flight{position:fixed;z-index:80;pointer-events:none;display:grid;place-items:center;padding:6px;border-radius:18px;background:rgba(31,21,14,.95);border:1px solid rgba(255,138,31,.5);box-shadow:0 8px 26px rgba(0,0,0,.28);color:#ff8a1f;will-change:transform,opacity}.motion-flight img{width:100%;height:100%;object-fit:contain}.motion-flight svg{width:60%;height:60%}.motion-heart{position:fixed;z-index:81;pointer-events:none;color:#ff655c;font-size:17px;line-height:1}
body #modal.show{animation:none}#modal .sheet{animation:none;transform-origin:center}#view{transform-origin:center;will-change:auto}#view.motion-routing{pointer-events:none}.order-route{position:relative;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:4px;margin:18px 0 22px;padding-top:2px;isolation:isolate}.order-route::before,.order-route::after{content:'';position:absolute;left:10%;top:16px;height:2px;z-index:-1;border-radius:2px}.order-route::before{width:80%;background:rgba(255,255,255,.12)}.order-route::after{width:calc(var(--route-progress)*.8);background:#ff8a1f;transform-origin:left;animation:route-fill .8s cubic-bezier(.22,1,.36,1) both}.route-step{display:flex;align-items:center;flex-direction:column;gap:7px;text-align:center;font-size:12px;color:var(--muted);overflow-wrap:anywhere}.route-step>span{display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:#19120e;border:1px solid rgba(255,255,255,.16);font-size:13px;animation:route-step .5s cubic-bezier(.22,1,.36,1) both;animation-delay:calc(var(--step)*65ms)}.route-step.done>span,.route-step.current>span{border-color:#ff8a1f;background:#ff8a1f;color:#211208}.route-step.current{color:#f5ece2}.route-step.current>span{box-shadow:0 0 0 5px rgba(255,138,31,.12)}@keyframes route-fill{from{transform:scaleX(0)}to{transform:scaleX(1)}}@keyframes route-step{from{opacity:0;transform:scale(.72) translateY(4px)}to{opacity:1;transform:scale(1) translateY(0)}}
@media(prefers-reduced-motion:reduce){.order-route::after,.route-step>span,.model-loader{animation:none!important}.reveal-pending{opacity:1;transform:none}}
`;document.head.appendChild(style);
window.Print3DMotion={reduced,bounce,snapshot,fly,favorite,anchor,open,close,leaveView,color,cancelColor,reveal,view,captureNumbers,numbers,loading,model};
})();
