(function(){'use strict';
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const active=new WeakMap(),colors=new WeakMap();
function color(material,value){if(!material?.color)return;const previous=colors.get(material);if(previous)cancelAnimationFrame(previous.frame);const target=material.color.clone().set(value);if(reduced()){material.color.copy(target);colors.delete(material);return}
 const state={from:material.color.clone(),target,start:performance.now(),frame:0};colors.set(material,state);
 const tick=now=>{if(colors.get(material)!==state)return;const t=Math.min(1,(now-state.start)/480),ease=t*t*(3-2*t);material.color.copy(state.from).lerp(target,ease);if(t<1)state.frame=requestAnimationFrame(tick);else colors.delete(material)};state.frame=requestAnimationFrame(tick);
}
function cancelColor(material){const state=colors.get(material);if(state)cancelAnimationFrame(state.frame);colors.delete(material)}
function animate(node,frames,options){if(!node||reduced()||!node.animate)return null;active.get(node)?.cancel();const animation=node.animate(frames,options);active.set(node,animation);animation.finished.catch(()=>{}).finally(()=>{if(active.get(node)===animation)active.delete(node)});return animation}
function bounce(node){return animate(node,[{transform:'scale(1)'},{transform:'scale(.85)',offset:.16},{transform:'scale(1.19)',offset:.48},{transform:'scale(.97)',offset:.78},{transform:'scale(1)'}],{duration:540,easing:'cubic-bezier(.22,.8,.3,1)'})}
function snapshot(button){const media=button.closest('.pcard')?.querySelector('.pimg')||button.closest('.sheet')?.querySelector('.media')||button;return {rect:media.getBoundingClientRect(),src:media.querySelector('img')?.src}}
function fly(from,target,icon){if(!target)return;if(reduced()){return}const to=target.getBoundingClientRect(),header=target.closest('.hdr');let ty=to.top+to.height/2;
 if(header){const transform=getComputedStyle(header).transform;if(transform!=='none')ty-=new DOMMatrixReadOnly(transform).m42;header.classList.remove('scroll-hidden')}
 const tx=to.left+to.width/2,size=Math.min(76,Math.max(36,from.rect.width*.3)),x=from.rect.left+from.rect.width/2-size/2,y=from.rect.top+from.rect.height/2-size/2;
 const flight=document.createElement('div');flight.className='motion-flight';flight.setAttribute('aria-hidden','true');Object.assign(flight.style,{left:x+'px',top:y+'px',width:size+'px',height:size+'px'});
 if(from.src){const img=document.createElement('img');img.src=from.src;flight.appendChild(img)}else flight.innerHTML=icon;
 document.body.appendChild(flight);const dx=tx-x-size/2,dy=ty-y-size/2;
 const animation=flight.animate([{transform:'translate3d(0,0,0) scale(1)',opacity:1},{transform:`translate3d(${dx*.36}px,${Math.min(-60,dy*.4-65)}px,0) scale(.86)`,offset:.42,opacity:1},{transform:`translate3d(${dx}px,${dy}px,0) scale(.2)`,opacity:0}],{duration:760,easing:'cubic-bezier(.4,0,.2,1)'});
 animation.finished.then(()=>bounce(target)).catch(()=>{}).finally(()=>flight.remove());setTimeout(()=>flight.remove(),1000);
}
function favorite(button,on){bounce(button);if(!on||reduced()||!button)return;const rect=button.getBoundingClientRect();for(let i=0;i<7;i++){const dot=document.createElement('span');dot.className='motion-heart';dot.textContent=i%2?'♥':'•';dot.setAttribute('aria-hidden','true');Object.assign(dot.style,{left:(rect.left+rect.width/2)+'px',top:(rect.top+rect.height/2)+'px'});document.body.appendChild(dot);const angle=i/7*Math.PI*2,dist=26+i%3*7;const anim=dot.animate([{transform:'translate(-50%,-50%) scale(.3)',opacity:1},{transform:`translate(calc(-50% + ${Math.cos(angle)*dist}px),calc(-50% + ${Math.sin(angle)*dist-14}px)) scale(1)`,opacity:.8,offset:.62},{transform:`translate(calc(-50% + ${Math.cos(angle)*dist*1.2}px),calc(-50% + ${Math.sin(angle)*dist-30}px)) scale(.4)`,opacity:0}],{duration:620,easing:'ease-out'});anim.finished.catch(()=>{}).finally(()=>dot.remove());setTimeout(()=>dot.remove(),900)}}
function open(sheet,source){if(!sheet||reduced())return;const box=sheet.getBoundingClientRect(),from=source?.getBoundingClientRect();const dx=from?from.left+from.width/2-box.left-box.width/2:0,dy=from?from.top+from.height/2-box.top-box.height/2:24;
 animate(sheet,[{transform:`translate3d(${dx}px,${dy}px,0) scale(${from?Math.max(.3,Math.min(.85,from.width/box.width)):.94})`,opacity:0},{transform:'translate3d(0,-3px,0) scale(1.012)',opacity:1,offset:.76},{transform:'translate3d(0,0,0) scale(1)',opacity:1}],{duration:540,easing:'cubic-bezier(.22,1,.36,1)'});
}
function close(sheet){return animate(sheet,[{transform:'translateY(0) scale(1)',opacity:1},{transform:'translateY(16px) scale(.97)',opacity:0}],{duration:170,easing:'ease-in'})}
document.addEventListener('click',e=>{const button=e.target.closest('button');if(button&&!button.disabled)bounce(button)},true);
const style=document.createElement('style');style.textContent=`
.motion-flight{position:fixed;z-index:80;pointer-events:none;display:grid;place-items:center;padding:6px;border-radius:18px;background:rgba(31,21,14,.95);border:1px solid rgba(255,138,31,.5);box-shadow:0 8px 26px rgba(0,0,0,.28);color:#ff8a1f;will-change:transform,opacity}.motion-flight img{width:100%;height:100%;object-fit:contain}.motion-flight svg{width:60%;height:60%}.motion-heart{position:fixed;z-index:81;pointer-events:none;color:#ff655c;font-size:17px;line-height:1}
#modal .sheet{animation:none;transform-origin:center}.order-route{position:relative;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:4px;margin:18px 0 22px;padding-top:2px;isolation:isolate}.order-route::before,.order-route::after{content:'';position:absolute;left:10%;top:16px;height:2px;z-index:-1;border-radius:2px}.order-route::before{width:80%;background:rgba(255,255,255,.12)}.order-route::after{width:calc(var(--route-progress)*.8);background:#ff8a1f;transform-origin:left;animation:route-fill .8s cubic-bezier(.22,1,.36,1) both}.route-step{display:flex;align-items:center;flex-direction:column;gap:7px;text-align:center;font-size:12px;color:var(--muted);overflow-wrap:anywhere}.route-step>span{display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:#19120e;border:1px solid rgba(255,255,255,.16);font-size:13px;animation:route-step .5s cubic-bezier(.22,1,.36,1) both;animation-delay:calc(var(--step)*65ms)}.route-step.done>span,.route-step.current>span{border-color:#ff8a1f;background:#ff8a1f;color:#211208}.route-step.current{color:#f5ece2}.route-step.current>span{box-shadow:0 0 0 5px rgba(255,138,31,.12)}@keyframes route-fill{from{transform:scaleX(0)}to{transform:scaleX(1)}}@keyframes route-step{from{opacity:0;transform:scale(.72) translateY(4px)}to{opacity:1;transform:scale(1) translateY(0)}}
@media(prefers-reduced-motion:reduce){.order-route::after,.route-step>span{animation:none!important}}
`;document.head.appendChild(style);
window.Print3DMotion={reduced,bounce,snapshot,fly,favorite,open,close,color,cancelColor};
})();
