(function(root){'use strict';
const defaults={tray:{items:['AA','nano'],columns:2,clearance:.2,wall:1.2,bottom:1.2},vase:{height:150,wall:1.6,bottom:2,twist:0,lobes:6,ribs:0,amplitude:.12,shape:'flower',profile:[{z:0,radius:35},{z:.5,radius:55},{z:1,radius:32}]}};
let state=JSON.parse(JSON.stringify(defaults));try{const saved=JSON.parse(localStorage.getItem('print3d:studio')||'null');if(saved)for(const k of ['tray','vase'])state[k]={...state[k],...saved[k]}}catch(e){}
let mode='tray',host=null,model=null,viewer=null,selected=1,timer=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{localStorage.setItem('print3d:studio',JSON.stringify(state))}catch(e){}};
const range=(key,label,min,max,step)=>`<label class="f studio-slider"><span>${label}</span><div><input type="range" data-p="${key}" min="${min}" max="${max}" step="${step}" value="${state[mode][key]}"><input type="number" data-p="${key}" min="${min}" max="${max}" step="${step}" value="${state[mode][key]}"></div></label>`;
function html(kind){mode=kind;const vase=mode==='vase';return `<section class="card2 studio" id="studio"><div><span class="pill">PRINT3D / ${vase?'VASE':'FIT TRAY'}</span><h2>${vase?'Вази й візерунки':'Лотки під предмети'}</h2>
${vase?`<p class="mut">Тягни помаранчеві вузли профілю пальцем: вбік — ширина, вгору/вниз — розташування. Крайні вузли задають низ і верх.</p><svg id="vase-profile" viewBox="0 0 280 320" role="img" aria-label="Перетягування форми вази"></svg><div class="rw"><button class="chip" data-studio="node-add">+ Вузол</button><button class="chip" data-studio="node-remove">− Вузол</button></div><label class="f"><span>Форма перерізу</span><select data-p="shape">${[['circle','Коло'],['flower','Квітка'],['square','Квадрат'],['polygon','Багатокутник']].map(([k,n])=>`<option value="${k}" ${state.vase.shape===k?'selected':''}>${n}</option>`).join('')}</select></label>${range('height','Висота, мм',20,400,1)}${range('lobes','Пелюстки квітки / грані багатокутника',3,24,1)}${range('amplitude','Виразність візерунка',0,.28,.01)}${range('twist','Закручування, °',-360,360,1)}${range('ribs','Декоративні ребра',0,96,1)}${range('wall','Товщина стінки, мм',.8,4,.1)}${range('bottom','Товщина дна, мм',.8,5,.1)}`:
`<p class="mut">Батарейки лежать горизонтально. SIM-карти — у неглибоких комірках із вирізом для виймання. Кожна комірка може мати свій тип.</p><div id="tray-items"></div><div class="rw"><select id="tray-add-type">${options('AA')}</select><button class="chip" data-studio="cell-add">+ Комірка</button></div>${range('columns','Комірок у ряду',1,6,1)}${range('clearance','Зазор на КОЖЕН бік, мм',.05,1,.05)}${range('wall','Товщина бортиків, мм',.8,3,.1)}${range('bottom','Товщина дна, мм',.8,2,.1)}<p class="mut">Для SIM враховано запас на габаритний допуск. Реальна посадка залежить від калібрування принтера — спершу надрукуй тестову комірку.</p><p class="mut"><a class="link" href="https://www.panasonic.com/global/energy/products/eneloop/en/lineup/eneloop.html" target="_blank" rel="noopener">Габарити батарейок</a> · <a class="link" href="https://www.etsi.org/deliver/etsi_ts/102200_102299/102221/14.02.00_60/ts_102221v140200p.pdf" target="_blank" rel="noopener">Формати SIM ETSI</a></p>`}
<p id="studio-error" class="err" role="status"></p><p id="studio-info" class="mut"></p><div class="rw" style="flex-wrap:wrap"><button class="btn" data-studio="download">Завантажити STL</button>${!vase?'<button class="chip" data-studio="sample">Тест першої комірки</button>':''}<button class="chip" data-studio="reset">Скинути</button></div></div><div class="studio-right"><div id="studio-preview" class="org-preview">Завантаження 3D…</div><div class="rw"><button class="chip" data-studio="fit">Повернути камеру</button><label class="f"><span>Колір прев’ю</span><input type="color" id="studio-color" value="#ff8a1f"></label></div><p class="mut">STL у міліметрах · колір лише для прев’ю</p></div></section>`}
function options(type){return Object.entries(root.Print3DGenerators.PRESETS).map(([key,p])=>`<option value="${key}" ${key===type?'selected':''}>${escape(p.label)}</option>`).join('')}
function drawCells(){const list=host.querySelector('#tray-items');if(list)list.innerHTML=state.tray.items.map((type,i)=>`<div class="rw"><span class="pill">${i+1}</span><select data-slot="${i}">${options(type)}</select><button class="chip" data-studio="cell-remove" data-index="${i}" aria-label="Видалити комірку ${i+1}">×</button></div>`).join('')}
function drawProfile(){const svg=host.querySelector('#vase-profile');if(!svg)return;const p=state.vase.profile,point=q=>[140+q.radius*1.05,290-q.z*260];
const right=p.map(point),left=p.map(q=>[140-q.radius*1.05,290-q.z*260]).reverse();svg.innerHTML=`<path d="M ${[...right,...left].map(q=>q.join(' ')).join(' L ')} Z" fill="rgba(255,138,31,.12)" stroke="#ff8a1f" stroke-width="2"/><path d="M140 20V300" stroke="rgba(255,255,255,.2)" stroke-dasharray="4 5"/>${p.map((q,i)=>{const [x,y]=point(q);return `<circle data-node="${i}" cx="${x}" cy="${y}" r="${i===selected?10:8}" fill="#ff8a1f" stroke="${i===selected?'white':'#201610'}" stroke-width="2"/><text x="${Math.min(x+14,235)}" y="${y-12}" fill="#c7b5a4" font-size="11">Ø${(q.radius*2).toFixed(0)}</text>`}).join('')}`}
function refresh(){if(!host?.isConnected)return;model=null;try{model=root.Print3DGenerators[mode](state[mode]);host.querySelector('#studio-error').textContent='';const p=model.parameters;host.querySelector('#studio-info').textContent=`${p.width.toFixed(1)} × ${p.depth.toFixed(1)} × ${p.height.toFixed(1)} мм`+(p.width>256||p.depth>256||p.height>256?' · Перевір габарити свого принтера':'');if(viewer)viewer.update(model);save()}catch(e){host.querySelector('#studio-error').textContent=e.message;host.querySelector('#studio-info').textContent='';if(viewer)viewer.mesh.visible=false}host.querySelector('[data-studio="download"]').disabled=!model}
function schedule(){if(timer)return;timer=setTimeout(()=>{timer=null;refresh()},70)}
function download(sample=false){clearTimeout(timer);timer=null;refresh();if(!model)return;let result=model;
 if(sample)result=root.Print3DGenerators.tray({...state.tray,items:[state.tray.items[0]],columns:1});const url=URL.createObjectURL(new Blob([root.Print3DOrganizer.stl(result)],{type:'model/stl'})),link=document.createElement('a');link.href=url;link.download=`Print3D-${mode}${sample?'-test':''}.stl`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),15000)}
function onClick(e){const button=e.target.closest('[data-studio]');if(!button)return;const action=button.dataset.studio;
 if(action==='download'||action==='sample')return download(action==='sample');if(action==='fit')return viewer?.fit();
 if(action==='cell-add'){if(state.tray.items.length>=24)return;state.tray.items.push(host.querySelector('#tray-add-type').value);drawCells()}
 if(action==='cell-remove'){if(state.tray.items.length<=1)return;state.tray.items.splice(+button.dataset.index,1);drawCells()}
 if(action==='node-add'){const p=state.vase.profile;if(p.length>=12)return;let i=Math.min(selected,p.length-2);if(p[i+1].z-p[i].z<.08){i=p.findIndex((q,j)=>j<p.length-1&&p[j+1].z-q.z>=.08);if(i<0)return}p.splice(i+1,0,{z:(p[i].z+p[i+1].z)/2,radius:(p[i].radius+p[i+1].radius)/2});selected=i+1;drawProfile()}
 if(action==='node-remove'){const p=state.vase.profile;if(selected<=0||selected>=p.length-1)return;p.splice(selected,1);selected=Math.min(selected,p.length-2);drawProfile()}
 if(action==='reset'){state[mode]=JSON.parse(JSON.stringify(defaults[mode]));host.querySelectorAll('[data-p]').forEach(input=>input.value=state[mode][input.dataset.p]);selected=1;drawCells();drawProfile()}
 refresh();if(action==='reset')viewer?.fit();
}
function onInput(e){const input=e.target;if(input.id==='studio-color'){if(viewer)viewer.material.color.set(input.value);return}
 if(input.dataset.slot!==undefined){state.tray.items[+input.dataset.slot]=input.value;return refresh()}
 const key=input.dataset.p;if(!key)return;state[mode][key]=key==='shape'?input.value:input.value===''?NaN:Number(input.value);host.querySelectorAll(`[data-p="${key}"]`).forEach(other=>{if(other!==input)other.value=input.value});schedule()}
function profileEvents(){const svg=host.querySelector('#vase-profile');if(!svg)return;let dragging=null;
 svg.onpointerdown=e=>{const node=e.target.closest('[data-node]');if(!node)return;selected=+node.dataset.node;dragging=selected;svg.setPointerCapture(e.pointerId);drawProfile();e.preventDefault()};
 svg.onpointermove=e=>{if(dragging===null)return;const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const pos=pt.matrixTransform(svg.getScreenCTM().inverse()),p=state.vase.profile,q=p[dragging];q.radius=Math.max(8,Math.min(120,(pos.x-140)/1.05));if(dragging>0&&dragging<p.length-1)q.z=Math.max(p[dragging-1].z+.04,Math.min(p[dragging+1].z-.04,(290-pos.y)/260));drawProfile();schedule();e.preventDefault()};
 const end=()=>{dragging=null;refresh()};svg.onpointerup=end;svg.onpointercancel=end;
}
async function mount(kind,load3){dispose();mode=kind;host=document.getElementById('studio');if(!host)return;const current=host;host.addEventListener('click',onClick);host.addEventListener('input',onInput);drawCells();drawProfile();profileEvents();refresh();
 try{const {T,OrbitControls}=await load3();if(!current.isConnected||host!==current)return;const area=current.querySelector('#studio-preview'),scene=new T.Scene(),renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));area.innerHTML='';area.appendChild(renderer.domElement);renderer.domElement.style.touchAction='none';const camera=new T.PerspectiveCamera(42,1,.1,10000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.maxDistance=4000;controls.minDistance=10;
 scene.add(new T.HemisphereLight(0xffffff,0x59616c,2.2));const light=new T.DirectionalLight(0xffffff,2.5);light.position.set(200,400,300);scene.add(light);const material=new T.MeshStandardMaterial({color:0xff8a1f,roughness:.6,metalness:.03}),mesh=new T.Mesh(new T.BufferGeometry(),material);scene.add(mesh);let dead=false,first=true;
 const fit=()=>{const p=model?model.parameters:{width:100,depth:100,height:100},span=Math.max(p.width,p.depth,p.height),distance=span*2/Math.min(1,Math.max(.3,area.clientWidth/area.clientHeight));camera.position.set(distance*.65,p.height+distance*.65,distance*.85);controls.target.set(0,p.height*.4,0);controls.update()};
 const resize=()=>{const w=Math.max(1,area.clientWidth),h=Math.max(1,area.clientHeight);renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(area);resize();
 viewer={mesh,material,fit,update(m){const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(Float32Array.from(m.vertices),3));g.setIndex(m.triangles);const flat=g.toNonIndexed();g.dispose();if(!m.centered)flat.translate(-m.parameters.width/2,-m.parameters.depth/2,0);flat.rotateX(-Math.PI/2);flat.computeVertexNormals();mesh.geometry.dispose();mesh.geometry=flat;mesh.visible=true;if(first){first=false;fit()}},dispose(){dead=true;observer.disconnect();controls.dispose();mesh.geometry.dispose();material.dispose();renderer.dispose()}};refresh();
 function loop(){if(dead)return;if(!current.isConnected){dispose();return}controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}loop();
 }catch(e){if(current.isConnected)current.querySelector('#studio-preview').textContent='3D недоступне. STL можна завантажити.';console.error(e)}
}
function dispose(){clearTimeout(timer);timer=null;if(viewer){viewer.dispose();viewer=null}host=null;model=null}
root.Print3DStudio={html,mount,dispose};
})(window);
