const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('../generators.js'),{stl}=require('../organizer.js');
const tray={items:['AA','nano','AAA','micro','mini'],columns:3,clearance:.2,wall:1.2,bottom:1.2};
const vase={height:150,wall:1.6,bottom:2,twist:90,lobes:6,ribs:8,amplitude:.12,shape:'flower',profile:[{z:0,radius:35},{z:.5,radius:55},{z:1,radius:32}]};
function verify(m){const edges=new Map(),v=m.vertices,t=m.triangles;let volume=0;for(let i=0;i<t.length;i+=3){const ids=t.slice(i,i+3),[a,b,c]=ids.map(k=>k*3),u=[v[b]-v[a],v[b+1]-v[a+1],v[b+2]-v[a+2]],w=[v[c]-v[a],v[c+1]-v[a+1],v[c+2]-v[a+2]],cross=[u[1]*w[2]-u[2]*w[1],u[2]*w[0]-u[0]*w[2],u[0]*w[1]-u[1]*w[0]];assert.ok(Math.hypot(...cross)>1e-9,'degenerate face');volume+=(v[a]*(v[b+1]*v[c+2]-v[b+2]*v[c+1])+v[a+1]*(v[b+2]*v[c]-v[b]*v[c+2])+v[a+2]*(v[b]*v[c+1]-v[b+1]*v[c]))/6;for(let j=0;j<3;j++){const a=ids[j],b=ids[(j+1)%3],k=[Math.min(a,b),Math.max(a,b)].join(','),e=edges.get(k)||[0,0];e[0]++;e[1]+=a<b?1:-1;edges.set(k,e)}}for(const e of edges.values()){assert.equal(e[0],2);assert.equal(e[1],0)}assert.ok(volume>0);const binary=stl(m);assert.equal(binary.byteLength,84+t.length/3*50)}
test('mixed trays and single calibration cells are closed printable solids',()=>{for(const columns of [1,2,3,6])verify(G.tray({...tray,columns}));verify(G.tray({...tray,items:['nano'],columns:1}))});
test('every cavity keeps preset maximum size plus clearance on each side',()=>{const m=G.tray(tray);for(const c of m.cells){const p=G.PRESETS[c.type];assert.ok(Math.abs(c.w-p.width-.4)<1e-8);assert.ok(Math.abs(c.d-p.depth-.4)<1e-8)}assert.equal(G.PRESETS.AA.width,50.5);assert.equal(G.PRESETS.AAA.depth,10.5)});
test('circle, flower, square and polygon vases have closed bottoms and open mouths',()=>{for(const shape of ['circle','flower','square','polygon'])verify(G.vase({...vase,shape}));const m=G.vase(vase);assert.equal(Math.max(...m.vertices.filter((_,i)=>i%3===2)),150)});
test('profile nodes, twist and ribs actually alter the exported mesh',()=>{const a=G.vase(vase),b=G.vase({...vase,twist:0,ribs:0});assert.notDeepEqual(a.vertices,b.vertices);verify(G.vase({...vase,profile:[{z:0,radius:25},{z:.3,radius:40},{z:.7,radius:30},{z:1,radius:20}]}))});
test('invalid preset geometry cannot create a broken STL',()=>{assert.throws(()=>G.tray({...tray,clearance:-.1}));assert.throws(()=>G.tray({...tray,items:['unknown']}));assert.throws(()=>G.vase({...vase,height:NaN}));assert.throws(()=>G.vase({...vase,profile:[{z:0,radius:35},{z:0,radius:32}]}))});
