const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(reduced=false){const nodes=new Map();const document={querySelector:s=>nodes.get(s),addEventListener(){},createElement:()=>({}),head:{appendChild(){}}},window={};const ctx={window,document,matchMedia:()=>({matches:reduced}),CSS:{escape:x=>x},innerWidth:1000,innerHeight:800,getComputedStyle:n=>({transform:n.currentTransform||'none',opacity:n.currentOpacity||'1',backgroundColor:'rgba(0,0,0,.45)'})};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../motion.js'),'utf8'),ctx);return {M:window.Print3DMotion,nodes}}
function element(rect,dataset={}){return {tagName:'BUTTON',dataset,isConnected:true,bounds:rect,animations:[],getBoundingClientRect(){return this.bounds},animate(frames,options){let resolve,reject;const a={frames,options,cancelled:false,finished:new Promise((r,j)=>{resolve=r;reject=j}),finish(){resolve()},cancel(){this.cancelled=true;reject(Error('cancelled'))}};this.animations.push(a);return a}}}
test('modal closes to its actual product card and re-resolves a rebuilt opener',async()=>{const {M,nodes}=setup(),card=element({left:100,top:200,width:200,height:240},{a:'open',id:'5'});card.tagName='DIV';const sheet=element({left:200,top:100,width:600,height:400});M.open(sheet,card);sheet.animations[0].finish();await Promise.resolve();card.isConnected=false;const replacement=element({left:300,top:250,width:200,height:240});nodes.set('div[data-a="open"][data-id="5"]',replacement);const closing=M.close(sheet);assert.equal(closing.options.fill,'forwards');assert.equal(closing.frames.at(-1).transform,'translate3d(-100px,70px,0) scale(0.3333333333333333,0.6)');closing.finish();await Promise.resolve();M.open(sheet,card);assert.ok(closing.cancelled,'completed exit fill must be cleared when reopening')});
test('view folds to its own opener and the next view unfolds from the newly clicked button',async()=>{const {M}=setup(),root=element({left:100,top:100,width:800,height:600}),profile=element({left:800,top:20,width:40,height:40},{a:'tab',n:'prof'}),cart=element({left:740,top:20,width:40,height:40},{a:'tab',n:'cart'});M.view(root,'prof:info',M.anchor(profile));root.animations[0].finish();await Promise.resolve();const leaving=M.leaveView(root),exit=root.animations.at(-1);assert.equal(exit.frames.at(-1).transform,'translate3d(320px,-360px,0) scale(0.05,0.06666666666666667)');exit.finish();await leaving;M.view(root,'cart:info',M.anchor(cart));assert.ok(exit.cancelled);assert.equal(root.animations.at(-1).frames[0].transform,'translate3d(260px,-360px,0) scale(0.05,0.06666666666666667)')});
test('closing during entrance uses the current transform and reduced motion skips morphs',()=>{const {M}=setup(),sheet=element({left:200,top:100,width:600,height:400}),button=element({left:400,top:100,width:100,height:40});M.open(sheet,button);sheet.currentTransform='matrix(.5,0,0,.5,40,20)';sheet.currentOpacity='.6';const closing=M.close(sheet);assert.equal(closing.frames[0].transform,sheet.currentTransform);assert.equal(closing.frames[0].opacity,'.6');assert.ok(sheet.animations[0].cancelled);const quiet=setup(true).M,node=element({left:0,top:0,width:50,height:50});quiet.open(node,button);assert.equal(quiet.close(node),null);assert.equal(node.animations.length,0)});
test('rapid navigation commits only the latest target and releases the interaction lock',async()=>{
 const source=fs.readFileSync(require.resolve('../app.js'),'utf8'),segment=source.slice(source.indexOf('let navigationEpoch='),source.indexOf('const go='));let finishFirst,finishSecond,exits=0;const events=[],classes=new Set(),view={classList:{add:s=>classes.add(s),remove:s=>classes.delete(s)}};
 const context={view,Print3DMotion:{anchor:x=>x,leaveView:()=>new Promise(resolve=>{if(exits++===0)finishFirst=resolve;else finishSecond=resolve})},closeModal:()=>Promise.resolve(),render:async transition=>events.push(transition.origin),Promise};vm.createContext(context);vm.runInContext(segment,context);
 const first=context.navigate(()=>events.push('prof'),'profile-button'),second=context.navigate(()=>events.push('cart'),'cart-button');finishFirst();await first;assert.equal(events.length,0);assert.ok(classes.has('motion-routing'));finishSecond();await second;assert.deepEqual(events,['cart','cart-button']);assert.ok(!classes.has('motion-routing'));
});
