const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),G=require('../generators.js');
const original=fs.readFileSync(require.resolve('../studio.js'),'utf8');
function setup(saved){
 const svg={innerHTML:'',setPointerCapture(id){this.capture=id},hasPointerCapture(id){return this.capture===id},releasePointerCapture(){this.capture=null},getScreenCTM(){return {inverse(){return {}}}},createSVGPoint(){return {matrixTransform(){return {x:this.x,y:this.y}}}}},button={},fields={'#vase-profile':svg,'[data-studio="node-remove"]':button,'#studio-error':{},'#studio-info':{},'[data-studio="download"]':{}},host={isConnected:true,querySelector:s=>fields[s],querySelectorAll:()=>[]};
 let persisted=saved;const window={Print3DGenerators:G},context={window,localStorage:{getItem:()=>persisted||null,setItem:(key,value)=>persisted=value},setTimeout:()=>1,clearTimeout(){},console};vm.createContext(context);
 const source=original.replace('root.Print3DStudio={html,mount,dispose};','root.Print3DStudio={html,mount,dispose};root.testProfile={get:()=>state.vase.profile,add:addProfileNode,click:onClick,select:i=>selected=i,start:h=>{host=h;mode="vase";drawProfile();profileEvents()}};');vm.runInContext(source,context);window.testProfile.start(host);return {api:window.testProfile,svg,button,get saved(){return persisted}};
}
const remove=api=>api.click({target:{closest:()=>({dataset:{studio:'node-remove'}})}});
test('click position sets radius and height; deletion follows creation order after selection and reload',()=>{const s=setup();assert.equal(s.button.disabled,true);assert.equal(s.api.add(182,225),true);assert.equal(s.api.add(87.5,95),true);const p=s.api.get();assert.equal(p.length,5);assert.ok(Math.abs(p[1].z-.25)<1e-8);assert.equal(p[1].radius,40);assert.equal(p[3].radius,50);s.api.select(1);remove(s.api);assert.equal(s.api.get().length,4);assert.ok(!s.api.get().some(q=>q.z===.75));const restored=setup(s.saved);remove(restored.api);assert.equal(restored.api.get().length,3);assert.deepEqual(Array.from(restored.api.get(),q=>q.z),[0,.5,1]);assert.equal(restored.button.disabled,true);remove(restored.api);assert.equal(restored.api.get().length,3)});
test('SVG taps create nodes but existing-node drags and cancelled gestures do not',()=>{const s=setup(),empty={closest:()=>null},event=(x,y,target=empty)=>({pointerId:1,button:0,clientX:x,clientY:y,target,preventDefault(){}});s.svg.onpointerdown(event(182,225));s.svg.onpointerup(event(182,225));assert.equal(s.api.get().length,4);s.svg.onpointerdown(event(185,100));s.svg.onpointercancel(event(185,100));assert.equal(s.api.get().length,4);s.svg.onpointerdown(event(180,130));s.svg.onpointerup(event(200,130));assert.equal(s.api.get().length,4);const node={closest:()=>({dataset:{node:'1'}})};s.svg.onpointerdown(event(182,225,node));s.svg.onpointermove(event(192.5,220,node));s.svg.onpointerup(event(192.5,220,node));assert.equal(s.api.get().length,4);assert.equal(s.api.get()[1].radius,50);assert.equal(s.api.add(200,290),false);assert.equal(s.api.get().length,4)});
