const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
test('editor selects individual items, restricts wall axes, commits transforms and restores camera controls',()=>{
 class V{constructor(x=0,y=0,z=0){this.set(x,y,z)}set(x,y,z){Object.assign(this,{x,y,z});return this}toArray(){return [this.x,this.y,this.z]}clone(){return new V(this.x,this.y,this.z)}copy(v){return this.set(v.x,v.y,v.z)}add(v){return this.set(this.x+v.x,this.y+v.y,this.z+v.z)}sub(v){return this.set(this.x-v.x,this.y-v.y,this.z-v.z)}multiplyScalar(n){return this.set(this.x*n,this.y*n,this.z*n)}length(){return Math.hypot(this.x,this.y,this.z)}setLength(n){return this.multiplyScalar(n/this.length())}}
 class Geometry{dispose(){this.disposed=true}}
 class Object3D{constructor(){this.position=new V();this.rotation=new V();this.scale=new V(1,1,1)}updateMatrixWorld(){}}
 class Element{constructor(){this.style={};this.children=[];this.listeners={};this.classList={toggle(){}}}appendChild(e){this.children.push(e)}set innerHTML(v){this.html=v;this.select=new Element();this.status=new Element();this.buttons=['translate','rotate','scale'].map(mode=>{const b=new Element();b.dataset={mode};return b})}querySelector(s){return s==='canvas'?this.canvas:s==='select'?this.select:this.status}querySelectorAll(){return this.buttons}replaceChildren(...c){this.children=c}addEventListener(k,f){this.listeners[k]=f}removeEventListener(k){delete this.listeners[k]}remove(){this.removed=true}}
 let gizmo;class TransformControls extends Object3D{constructor(){super();gizmo=this;this.events={}}setSize(){}setTranslationSnap(){}setRotationSnap(){}setScaleSnap(){}setMode(m){this.mode=m}setSpace(s){this.space=s}attach(p){this.object=p}detach(){this.object=null}addEventListener(k,f){this.events[k]=f}dispose(){this.disposed=true}}
 class LineSegments extends Object3D{constructor(geometry,material){super();this.geometry=geometry;this.material=material}}
 const T={Object3D,Vector3:V,Vector2:V,LineSegments,BufferGeometry:Geometry,LineBasicMaterial:Geometry,BoxGeometry:Geometry,CylinderGeometry:Geometry,EdgesGeometry:Geometry,Raycaster:class{}};
 const document={createElement:()=>new Element(),head:new Element()},window={};vm.runInNewContext(fs.readFileSync(require.resolve('../drag-handles.js'),'utf8'),{document,window,Option:class{constructor(label,value){this.label=label;this.value=value}}});
 const host=new Element();host.canvas=new Element();const scene={add(){},remove(){}},controls={enabled:true,target:new V(),minDistance:5,maxDistance:100,update(){}};const items=[{id:'x0',label:'Wall',axes:['x'],position:[5,10,0],size:[2,20,100]},{id:'cell0',label:'AA',axes:['x','z'],position:[20,10,20],size:[16,20,16],round:true,scale:true}];let edit;
 const editor=window.Print3DWallHandles.mount({T,TransformControls,host,scene,camera:{position:new V(30,30,30)},controls,mesh:{},getItems:()=>items,onTransform(id,value,mode){edit={id,value,mode};items.find(x=>x.id===id).position=value.position},fit(){}});editor.update();editor.choose('x0');assert.equal(gizmo.object.position.x,5);assert.equal(gizmo.showX,true);assert.equal(gizmo.showZ,false);
 gizmo.events['dragging-changed']({value:true});assert.equal(controls.enabled,false);gizmo.object.position.x=12;gizmo.events.objectChange();assert.equal(edit.id,'x0');assert.equal(edit.value.position[0],12);assert.equal(items[1].position[0],20);gizmo.events['dragging-changed']({value:false});assert.equal(controls.enabled,true);
 editor.choose('cell0');const panel=host.children[0],scale=panel.buttons[2];panel.onclick({target:{closest:()=>scale}});assert.equal(gizmo.mode,'scale');assert.equal(gizmo.showZ,false);gizmo.object.scale.x=1.2;gizmo.events.objectChange();assert.equal(edit.mode,'scale');assert.equal(edit.id,'cell0');assert.equal(edit.value.scaleX,1.2);
 editor.dispose();assert.ok(gizmo.disposed);assert.ok(panel.removed);assert.deepEqual(Object.keys(host.canvas.listeners),[]);assert.equal(controls.enabled,true);
});
